In [30]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import os
from collections import Counter
import itertools
import collections

In [31]:
data = pd.read_csv('data.csv')
data.head(5)

,imdb_id,popularity,budget,revenue,original_title,cast,director,tagline,overview,runtime,genres,production_companies,release_date,vote_count,vote_average,release_year
0,tt0369610,32.985763,150000000,1513528810,Jurassic World,Chris Pratt|Bryce Dallas Howard|Irrfan Khan|Vi...,Colin Trevorrow,The park is open.,Twenty-two years after the events of Jurassic ...,124,Action|Adventure|Science Fiction|Thriller,Universal Studios|Amblin Entertainment|Legenda...,6/9/2015,5562,6.5,2015
1,tt1392190,28.419936,150000000,378436354,Mad Max: Fury Road,Tom Hardy|Charlize Theron|Hugh Keays-Byrne|Nic...,George Miller,What a Lovely Day.,An apocalyptic story set in the furthest reach...,120,Action|Adventure|Science Fiction|Thriller,Village Roadshow Pictures|Kennedy Miller Produ...,5/13/2015,6185,7.1,2015
2,tt2908446,13.112507,110000000,295238201,Insurgent,Shailene Woodley|Theo James|Kate Winslet|Ansel...,Robert Schwentke,One Choice Can Destroy You,Beatrice Prior must confront her inner demons ...,119,Adventure|Science Fiction|Thriller,Summit Entertainment|Mandeville Films|Red Wago...,3/18/2015,2480,6.3,2015
3,tt2488496,11.173104,200000000,2068178225,Star Wars: The Force Awakens,Harrison Ford|Mark Hamill|Carrie Fisher|Adam D...,J.J. Abrams,Every generation has a story.,Thirty years after defeating the Galactic Empi...,136,Action|Adventure|Science Fiction|Fantasy,Lucasfilm|Truenorth Productions|Bad Robot,12/15/2015,5292,7.5,2015
4,tt2820852,9.335014,190000000,1506249360,Furious 7,Vin Diesel|Paul Walker|Jason Statham|Michelle ...,James Wan,Vengeance Hits Home,Deckard Shaw seeks revenge against Dominic Tor...,137,Action|Crime|Thriller,Universal Pictures|Original Film|Media Rights ...,4/1/2015,2947,7.3,2015

In [32]:
len(data)

1890

# Предобработка датасета

In [6]:
answer_ls = [] # создадим список с ответами. сюда будем добавлять ответы по мере прохождения теста
# сюда можем вписать создание новых колонок в датасете

# 1. У какого фильма из списка самый большой бюджет?
Варианты ответов:
1. The Dark Knight Rises (tt1345836)
2. Spider-Man 3 (tt0413300)
3. Avengers: Age of Ultron (tt2395427)
4. The Warrior's Way	(tt1032751)
5. Pirates of the Caribbean: On Stranger Tides (tt1298650)

In [33]:
# тут вводим ваш ответ и добавлем в его список ответов (сейчас для примера стоит "1")
answer_ls.append(4)
data['budget'].max()
data[(data.budget==425000000)]['original_title'].unique()

array(["The Warrior's Way"], dtype=object)

# 2. Какой из фильмов самый длительный (в минутах)
1. The Lord of the Rings: The Return of the King	(tt0167260)
2. Gods and Generals	(tt0279111)
3. King Kong	(tt0360717)
4. Pearl Harbor	(tt0213149)
5. Alexander	(tt0346491)

In [34]:
answer_ls.append(2)
data['runtime'].max()
data[(data.runtime==214)]['original_title'].unique()

array(['Gods and Generals'], dtype=object)

# 3. Какой из фильмов самый короткий (в минутах)
Варианты ответов:

1. Home on the Range	tt0299172
2. The Jungle Book 2	tt0283426
3. Winnie the Pooh	tt1449283
4. Corpse Bride	tt0121164
5. Hoodwinked!	tt0443536

In [35]:
answer_ls.append(3)
data['runtime'].min()
data[(data.runtime==63)]['original_title'].unique()

array(['Winnie the Pooh'], dtype=object)

# 4. Средняя длительность фильма?

Варианты ответов:
1. 115
2. 110
3. 105
4. 120
5. 100

In [36]:
answer_ls.append(2)
data['runtime'].mean()

109.65343915343915

# 5. Средняя длительность фильма по медиане?
Варианты ответов:
1. 106
2. 112
3. 101
4. 120
5. 115

In [37]:
answer_ls.append(1)
print(data.runtime.median(axis=0))

106.5

# 6. Какой самый прибыльный фильм?
Варианты ответов:
1. The Avengers	tt0848228
2. Minions	tt2293640
3. Star Wars: The Force Awakens	tt2488496
4. Furious 7	tt2820852
5. Avatar	tt0499549

In [38]:
answer_ls.append(5)
data['profit'] = data.apply(lambda x: x.revenue - x.budget, axis=1)
data[data['profit'] == data['profit'].max()].original_title

239    Avatar
Name: original_title, dtype: object

# 7. Какой фильм самый убыточный?
Варианты ответов:
1. Supernova tt0134983
2. The Warrior's Way tt1032751
3. Flushed Away	tt0424095
4. The Adventures of Pluto Nash	tt0180052
5. The Lone Ranger	tt1210819

In [39]:
answer_ls.append(2)
data['profit'] = data.apply(lambda x: x.revenue - x.budget, axis=1)
data[data['profit'] == data['profit'].min()].original_title

491    The Warrior's Way
Name: original_title, dtype: object

# 8. Сколько всего фильмов в прибыли?
Варианты ответов:
1. 1478
2. 1520
3. 1241
4. 1135
5. 1398

In [40]:
answer_ls.append(1)
data['profit'] = data.apply(lambda x: x.revenue - x.budget, axis=1)
data[data['profit'] >0].original_title.value_counts()

Fantastic Four          2
The Gift                2
Spotlight               1
The House Bunny         1
The Raven               1
                       ..
The Smurfs 2            1
We Are Your Friends     1
The Dukes of Hazzard    1
Carol                   1
P.S. I Love You         1
Name: original_title, Length: 1476, dtype: int64

# 9. Самый прибыльный фильм в 2008 году?
Варианты ответов:
1. Madagascar: Escape 2 Africa	tt0479952
2. Iron Man	tt0371746
3. Kung Fu Panda	tt0441773
4. The Dark Knight	tt0468569
5. Mamma Mia!	tt0795421

In [41]:
answer_ls.append(4)
data['profit'] = data.apply(lambda x: x.revenue - x.budget, axis=1)

data[(data.profit.max())&(data.release_year==2008)].original_title

600                                      The Dark Knight
601                                              WALLÂ·E
602                                             Iron Man
603                                                Taken
604    Indiana Jones and the Kingdom of the Crystal S...
                             ...
716                                         Smart People
717                                         Nim's Island
718                                                 Igor
719                How to Lose Friends & Alienate People
720                          Welcome Home Roscoe Jenkins
Name: original_title, Length: 121, dtype: object

# 10. Самый убыточный фильм за период с 2012 по 2014 (включительно)?
Варианты ответов:
1. Winter's Tale	tt1837709
2. Stolen	tt1656186
3. Broken City	tt1235522
4. Upside Down	tt1374992
5. The Lone Ranger	tt1210819

In [42]:
answer_ls.append(5)
data['profit'] = data['revenue'] - data['budget']
data[( data.release_year>2011) & (data.release_year<2015)].sort_values('profit', ascending=False)[-10:].tail(5)

,imdb_id,popularity,budget,revenue,original_title,cast,director,tagline,overview,runtime,genres,production_companies,release_date,vote_count,vote_average,release_year,profit
1236,tt1308729,1.319947,55000000,9489829,Bullet to the Head,Sylvester Stallone|Sung Kang|Sarah Shahi|Adewa...,Walter Hill,Revenge Never Gets Old.,"After watching their respective partners die, ...",92,Action|Crime|Thriller,Dark Castle Entertainment|After Dark Films|IM ...,1/31/2013,347,5.2,2013,-45510171
1303,tt0884726,0.354271,70000000,18662027,Legends of Oz: Dorothy's Return,Lea Michele|Dan Aykroyd|Patrick Stewart|Hugh D...,Dan St. Pierre,There's trouble in OZ...,"Dorothy wakes up in post-tornado Kansas, only ...",88,Animation|Music|Family,Prana Animation Studios|Summertime Entertainment,6/13/2013,36,6.1,2013,-51337973
1008,tt1374992,1.690572,60000000,8106475,Upside Down,Kirsten Dunst|Jim Sturgess|Timothy Spall|James...,Juan Diego Solanas,Two worlds. One future.,In an alternate universe where twinned worlds ...,104,Romance|Science Fiction|Drama|Fantasy,Onyx Films|Studio 37|Jouror Productions|France...,9/27/2012,695,6.1,2012,-51893525
1215,tt0790736,1.689869,130000000,61648500,R.I.P.D.,Jeff Bridges|Ryan Reynolds|Kevin Bacon|Stephan...,Robert Schwentke,To protect and serve the living,A recently slain cop joins a team of undead po...,96,Fantasy|Action|Comedy|Crime,Universal Pictures|Original Film|Dark Horse En...,7/18/2013,876,5.3,2013,-68351500
1246,tt1210819,1.214510,255000000,89289910,The Lone Ranger,Johnny Depp|Armie Hammer|William Fichtner|Hele...,Gore Verbinski,Never Take Off the Mask,The Texas Rangers chase down a gang of outlaws...,149,Action|Adventure|Western,Walt Disney Pictures|Jerry Bruckheimer Films|I...,7/3/2013,1607,6.0,2013,-165710090

# 11. Какого жанра фильмов больше всего?
Варианты ответов:
1. Action
2. Adventure
3. Drama
4. Comedy
5. Thriller

In [43]:
answer_ls.append(3)
genre_counter = Counter()
for x in data.genres.str.split('|'):
    genre_counter += Counter(x)
genre_counter.most_common()

[('Drama', 782),
 ('Comedy', 683),
 ('Thriller', 597),
 ('Action', 583),
 ('Adventure', 416),
 ('Crime', 315),
 ('Romance', 308),
 ('Family', 260),
 ('Science Fiction', 248),
 ('Fantasy', 223),
 ('Horror', 176),
 ('Mystery', 168),
 ('Animation', 139),
 ('Music', 64),
 ('History', 62),
 ('War', 58),
 ('Western', 20),
 ('Documentary', 8),
 ('Foreign', 2)]

# 12. Какого жанра среди прибыльных фильмов больше всего?
Варианты ответов:
1. Drama
2. Comedy
3. Action
4. Thriller
5. Adventure

In [44]:
answer_ls.append(1)
data=data[data['profit']>0]
genre_counter = Counter()
for x in data.genres.str.split('|'):
    genre_counter += Counter(x)
genre_counter.most_common()

[('Drama', 560),
 ('Comedy', 551),
 ('Thriller', 446),
 ('Action', 444),
 ('Adventure', 337),
 ('Romance', 242),
 ('Crime', 231),
 ('Family', 226),
 ('Science Fiction', 195),
 ('Fantasy', 188),
 ('Horror', 150),
 ('Animation', 120),
 ('Mystery', 119),
 ('Music', 47),
 ('History', 46),
 ('War', 41),
 ('Western', 12),
 ('Documentary', 7)]

# 13. Кто из режиссеров снял больше всего фильмов?
Варианты ответов:
1. Steven Spielberg
2. Ridley Scott 
3. Steven Soderbergh
4. Christopher Nolan
5. Clint Eastwood

In [49]:
answer_ls.append(2)
director_counter = Counter()
for x in data.director.str.split('|'):
    director_counter += Counter(x)
director_counter.most_common()

[('Ridley Scott', 12),
 ('Steven Spielberg', 10),
 ('Clint Eastwood', 10),
 ('Steven Soderbergh', 10),
 ('Shawn Levy', 9),
 ('Tim Burton', 9),
 ('Antoine Fuqua', 8),
 ('Christopher Nolan', 8),
 ('Peter Jackson', 8),
 ('Michael Bay', 8),
 ('Brett Ratner', 8),
 ('Peter Farrelly', 8),
 ('Robert Rodriguez', 8),
 ('M. Night Shyamalan', 7),
 ('Bobby Farrelly', 7),
 ('Todd Phillips', 7),
 ('Adam Shankman', 7),
 ('Quentin Tarantino', 6),
 ('Francis Lawrence', 6),
 ('Adam McKay', 6),
 ('Robert Zemeckis', 6),
 ('Andy Fickman', 6),
 ('David Fincher', 6),
 ('Tim Story', 6),
 ('Zack Snyder', 6),
 ('Ron Howard', 6),
 ('Sam Raimi', 6),
 ('Joel Coen', 6),
 ('Louis Leterrier', 6),
 ('Dennis Dugan', 6),
 ('Paul W.S. Anderson', 6),
 ('Gore Verbinski', 6),
 ('Peter Segal', 6),
 ('Raja Gosnell', 6),
 ('J.J. Abrams', 5),
 ('Sam Mendes', 5),
 ('Jaume Collet-Serra', 5),
 ('F. Gary Gray', 5),
 ('Guy Ritchie', 5),
 ('Nancy Meyers', 5),
 ('Guillermo del Toro', 5),
 ('Bryan Singer', 5),
 ('Doug Liman', 5),
 ('Jon Favreau', 5),
 ('Carlos Saldanha', 5),
 ('Lasse HallstrÃ¶m', 5),
 ('Roland Emmerich', 5),
 ('Robert Luketic', 5),
 ('Steve Carr', 5),
 ('Tony Scott', 5),
 ('Martin Scorsese', 5),
 ('Danny Boyle', 5),
 ('Jon Turteltaub', 5),
 ('James Mangold', 5),
 ('Oliver Stone', 5),
 ('John Singleton', 5),
 ('Marc Forster', 5),
 ('Peter Berg', 5),
 ('Alejandro GonzÃ¡lez IÃ±Ã¡rritu', 4),
 ('Lana Wachowski', 4),
 ('Lilly Wachowski', 4),
 ('Chris Columbus', 4),
 ('Olivier Megaton', 4),
 ('Peyton Reed', 4),
 ('Brad Bird', 4),
 ('Matthew Vaughn', 4),
 ('Rob Letterman', 4),
 ('Tarsem Singh', 4),
 ('Judd Apatow', 4),
 ('John Erick Dowdle', 4),
 ('Boaz Yakin', 4),
 ('Anne Fletcher', 4),
 ('Ken Kwapis', 4),
 ('Wes Anderson', 4),
 ('Phil Lord', 4),
 ('Christopher Miller', 4),
 ('Luke Greenfield', 4),
 ('Eric Darnell', 4),
 ('Rob Marshall', 4),
 ('David Dobkin', 4),
 ('Nicholas Stoller', 4),
 ('Nick Cassavetes', 4),
 ('Rob Minkoff', 4),
 ('George Clooney', 4),
 ('David Yates', 4),
 ('David R. Ellis', 4),
 ('Ethan Coen', 4),
 ('David Twohy', 4),
 ('Jason Reitman', 4),
 ('Justin Lin', 4),
 ('Donald Petrie', 4),
 ('Tom McGrath', 4),
 ('Edward Zwick', 4),
 ('Andy Tennant', 4),
 ('Garry Marshall', 4),
 ('Jason Friedberg', 4),
 ('Aaron Seltzer', 4),
 ('Kevin Smith', 4),
 ('Jay Roach', 4),
 ('Andrew Adamson', 4),
 ('Simon West', 4),
 ('Keenen Ivory Wayans', 4),
 ('John Moore', 4),
 ('Rob Cohen', 4),
 ('D.J. Caruso', 4),
 ('Mark Waters', 4),
 ('Malcolm D. Lee', 4),
 ('Martin Campbell', 4),
 ('Mikael HÃ¥fstrÃ¶m', 4),
 ('Alexander Payne', 4),
 ('Len Wiseman', 4),
 ('Paul Greengrass', 4),
 ('George Miller', 3),
 ('Robert Schwentke', 3),
 ('James Wan', 3),
 ('Pierre Coffin', 3),
 ('Pete Docter', 3),
 ('Brad Peyton', 3),
 ('Neill Blomkamp', 3),
 ('Baltasar KormÃ¡kur', 3),
 ('Tom Hooper', 3),
 ('Paul Feig', 3),
 ('Gavin Hood', 3),
 ('Brian Helgeland', 3),
 ('Steve Martino', 3),
 ('Jonathan Levine', 3),
 ('David Ayer', 3),
 ('Neil Burger', 3),
 ('Jonathan Liebesman', 3),
 ('Matt Reeves', 3),
 ('Marc Webb', 3),
 ('Dean DeBlois', 3),
 ('Darren Aronofsky', 3),
 ('Frank Coraci', 3),
 ('Will Gluck', 3),
 ('Steve Pink', 3),
 ('Thomas Carter', 3),
 ('Randall Wallace', 3),
 ('McG', 3),
 ('John Lee Hancock', 3),
 ('Ruben Fleischer', 3),
 ('Chris Weitz', 3),
 ('Stephen Sommers', 3),
 ('Mark Neveldine', 3),
 ('Brian Taylor', 3),
 ('Conrad Vernon', 3),
 ('Michael Mann', 3),
 ('Kevin Macdonald', 3),
 ('James McTeigue', 3),
 ('NimrÃ³d Antal', 3),
 ('Tom Tykwer', 3),
 ('Rob Zombie', 3),
 ('Peter Chelsom', 3),
 ('Greg Mottola', 3),
 ('Jonathan Mostow', 3),
 ('Thor Freudenthal', 3),
 ('Marc Lawrence', 3),
 ('Chris Renaud', 3),
 ('Sylvester Stallone', 3),
 ('Chris Sanders', 3),
 ('Lee Unkrich', 3),
 ('Paul Weitz', 3),
 ('Mike Mitchell', 3),
 ('Joe Carnahan', 3),
 ('Ben Affleck', 3),
 ('Jon M. Chu', 3),
 ('Harald Zwart', 3),
 ('Roman Polanski', 3),
 ('Paul Haggis', 3),
 ('Alexandre Aja', 3),
 ('Tyler Perry', 3),
 ('Ben Stiller', 3),
 ('Dominic Sena', 3),
 ('Gary Fleder', 3),
 ('Brian Robbins', 3),
 ('Andrzej Bartkowiak', 3),
 ('Jesse Dylan', 3),
 ('Tim Hill', 3),
 ('Joe Johnston', 3),
 ('Andrew Stanton', 3),
 ('David Frankel', 3),
 ('Seth Gordon', 3),
 ('Woody Allen', 3),
 ('Bill Condon', 3),
 ('Wes Craven', 3),
 ('Stephen Daldry', 3),
 ('Joe Wright', 3),
 ('Kelly Asbury', 3),
 ('David Cronenberg', 3),
 ('Chris Wedge', 3),
 ('Barry Sonnenfeld', 3),
 ('Steven Brill', 3),
 ('Joel Schumacher', 3),
 ('Jeff Tremaine', 3),
 ('Ang Lee', 3),
 ('Stephen Frears', 3),
 ('Wolfgang Petersen', 3),
 ('Alan Taylor', 2),
 ('Kyle Balda', 2),
 ('Joss Whedon', 2),
 ('Kenneth Branagh', 2),
 ('Christopher McQuarrie', 2),
 ('Seth MacFarlane', 2),
 ('Wes Ball', 2),
 ('Elizabeth Banks', 2),
 ('Breck Eisner', 2),
 ('Tim Johnson', 2),
 ('Todd Haynes', 2),
 ('John Wells', 2),
 ('Denis Villeneuve', 2),
 ('Josh Trank', 2),
 ('Glenn Ficarra', 2),
 ('John Requa', 2),
 ('George Tillman, Jr.', 2),
 ('Genndy Tartakovsky', 2),
 ('Jessie Nelson', 2),
 ('Gil Kenan', 2),
 ('Sean Anders', 2),
 ('Mark Osborne', 2),
 ('Scott Cooper', 2),
 ('Simon Curtis', 2),
 ('Jason Moore', 2),
 ('Camille Delamarre', 2),
 ('Jonathan Demme', 2),
 ('Mike Binder', 2),
 ('James Gunn', 2),
 ('Joe Russo', 2),
 ('Anthony Russo', 2),
 ('Chris Williams', 2),
 ('Luc Besson', 2),
 ('Jake Kasdan', 2),
 ('Simon J. Smith', 2),
 ('Noam Murro', 2),
 ('Phillip Noyce', 2),
 ('Scott Waugh', 2),
 ('Anthony Stacchi', 2),
 ('Steven Quale', 2),
 ('Shana Feste', 2),
 ('Miguel Arteta', 2),
 ('Craig Gillespie', 2),
 ('Charles Martin Smith', 2),
 ('James Bobin', 2),
 ('Rupert Wyatt', 2),
 ('James Cameron', 2),
 ('Burr Steers', 2),
 ('Alex Proyas', 2),
 ('Duncan Jones', 2),
 ('P.J. Hogan', 2),
 ('Jim Sheridan', 2),
 ('Nora Ephron', 2),
 ('Betty Thomas', 2),
 ('Gary Winick', 2),
 ('Lee Daniels', 2),
 ('David S. Goyer', 2),
 ('John Hamburg', 2),
 ('Paul McGuigan', 2),
 ('Kevin Greutert', 2),
 ('Harold Ramis', 2),
 ('Patrick Lussier', 2),
 ('Walt Becker', 2),
 ('Lone Scherfig', 2),
 ('Marcus Nispel', 2),
 ('Joseph Kosinski', 2),
 ('Byron Howard', 2),
 ('Michael Apted', 2),
 ('Mike Newell', 2),
 ('Albert Hughes', 2),
 ('Allen Hughes', 2),
 ('David Slade', 2),
 ('Scott Stewart', 2),
 ('Michael Patrick King', 2),
 ('John Luessenhop', 2),
 ('Roger Michell', 2),
 ('Michael Lembeck', 2),
 ('John Madden', 2),
 ('Brian Levant', 2),
 ('Neil LaBute', 2),
 ('Tom Dey', 2),
 ('Eric Brevig', 2),
 ('Roger Kumble', 2),
 ('David Silverman', 2),
 ('Vicky Jenson', 2),
 ('Baz Luhrmann', 2),
 ('John A. Davis', 2),
 ('Cameron Crowe', 2),
 ('Victor Salva', 2),
 ('Lee Tamahori', 2),
 ('Iain Softley', 2),
 ('Ivan Reitman', 2),
 ('Frank Oz', 2),
 ('John Stockwell', 2),
 ('Catherine Hardwicke', 2),
 ('Phyllida Lloyd', 2),
 ('Timur Bekmambetov', 2),
 ('Kathryn Bigelow', 2),
 ('Scott Derrickson', 2),
 ('Gabriele Muccino', 2),
 ('David Gordon Green', 2),
 ('Mathieu Kassovitz', 2),
 ('Martin McDonagh', 2),
 ('Jon Hurwitz', 2),
 ('Hayden Schlossberg', 2),
 ('Jimmy Hayward', 2),
 ('Gus Van Sant', 2),
 ('Gina Prince-Bythewood', 2),
 ('Kirk De Micco', 2),
 ('Andrew Niccol', 2),
 ('John Lasseter', 2),
 ('Brad Furman', 2),
 ('Bennett Miller', 2),
 ('Chris Miller', 2),
 ('Michel Gondry', 2),
 ('David Bowers', 2),
 ('Craig Brewer', 2),
 ('Henry Joost', 2),
 ('Ariel Schulman', 2),
 ('John Whitesell', 2),
 ('Salim Akil', 2),
 ('George Lucas', 2),
 ('Wayne Wang', 2),
 ('Spike Jonze', 2),
 ('Carl Franklin', 2),
 ('Denzel Washington', 2),
 ('Tony Gilroy', 2),
 ('David O. Russell', 2),
 ('Gary Ross', 2),
 ('Kirk Jones', 2),
 ('Larry Charles', 2),
 ('Peter Lord', 2),
 ('Mark Steven Johnson', 2),
 ('David Zucker', 2),
 ('Bille Woodruff', 2),
 ('Richard Linklater', 2),
 ('Clark Johnson', 2),
 ('John Woo', 2),
 ('Nigel Cole', 2),
 ('Chris Buck', 2),
 ('Alfonso CuarÃ³n', 2),
 ('Brad Anderson', 2),
 ('Taylor Hackford', 2),
 ('Sofia Coppola', 2),
 ('Mark Dindal', 2),
 ('Nick Park', 2),
 ('Rob Reiner', 2),
 ('Kevin Rodney Sullivan', 2),
 ('James Wong', 2),
 ('Mel Gibson', 2),
 ('Darren Lynn Bousman', 2),
 ('Takashi Shimizu', 2),
 ('Richard Loncraine', 2),
 ('Danny Leiner', 2),
 ('Mike Nichols', 2),
 ('Michael Moore', 2),
 ('Jay Russell', 2),
 ('Richard LaGravenese', 2),
 ('Kevin Lima', 2),
 ('Colin Trevorrow', 1),
 ('Alex Garland', 1),
 ('Sam Taylor-Johnson', 1),
 ('Tom McCarthy', 1),
 ('Lenny Abrahamson', 1),
 ('Peter Sohn', 1),
 ('John Crowley', 1),
 ('Lee Toland Krieger', 1),
 ('Ilya Naishuller', 1),
 ('Jake Schreier', 1),
 ('Ericson Core', 1),
 ('Aleksander Bach', 1),
 ('Ryan Coogler', 1),
 ('Peter Landesman', 1),
 ('John Francis Daley', 1),
 ('Jonathan M. Goldstein', 1),
 ('Joel Edgerton', 1),
 ('Jocelyn Moorhouse', 1),
 ('Ari Sandel', 1),
 ('Ciaran Foy', 1),
 ('Doug Ellin', 1),
 ('Jeremy Garelick', 1),
 ('Michael Dougherty', 1),
 ('Dean Israelite', 1),
 ('Gregory Jacobs', 1),
 ('Gregory Plotkin', 1),
 ('Billy Ray', 1),
 ('Paul Tibbitt', 1),
 ('Leigh Whannell', 1),
 ('Nicholas Hytner', 1),
 ('David M. Rosenthal', 1),
 ('Etan Cohen', 1),
 ('Sarah Gavron', 1),
 ('Max Joseph', 1),
 ('Chad Stahelski', 1),
 ('David Leitch', 1),
 ('Don Hall', 1),
 ('Morten Tyldum', 1),
 ('Dan Gilroy', 1),
 ('Gareth Edwards', 1),
 ('Robert Stromberg', 1),
 ('Roger Donaldson', 1),
 ('Stiles White', 1),
 ('Patrick Hughes', 1),
 ('Sergey Bodrov', 1),
 ('James Marsh', 1),
 ('Gary Shore', 1),
 ('Scott Frank', 1),
 ('Paul King', 1),
 ('James DeMonaco', 1),
 ('Vic Armstrong', 1),
 ('R.J. Cutler', 1),
 ('Trish Sie', 1),
 ('Josh Boone', 1),
 ('JosÃ© Padilha', 1),
 ('Wally Pfister', 1),
 ('Angelina Jolie', 1),
 ('Ava DuVernay', 1),
 ('Michael Hoffman', 1),
 ('Theodore Melfi', 1),
 ('Graham Annable', 1),
 ('Brian A Miller', 1),
 ('Roberts Gannaway', 1),
 ('Sam Miller', 1),
 ('John R. Leonetti', 1),
 ('Stuart Beattie', 1),
 ('Tom Gormican', 1),
 ('Ben Falcone', 1),
 ('Christopher Spencer', 1),
 ('GrÃ©gory Levasseur', 1),
 ('Andrew Erwin', 1),
 ('Jon Erwin', 1),
 ('Dave Green', 1),
 ('Harold Cronk', 1),
 ('Matt Bettinelli-Olpin', 1),
 ('Tyler Gillett', 1),
 ('Patrick Tatopoulos', 1),
 ('Bob Peterson', 1),
 ('Shane Acker', 1),
 ('Ron Clements', 1),
 ('John Musker', 1),
 ('Henry Selick', 1),
 ('Richard Kelly', 1),
 ('Hoyt Yeatman', 1),
 ('Ricky Gervais', 1),
 ('Matthew Robinson', 1),
 ('Peter Billingsley', 1),
 ('Karyn Kusama', 1),
 ('Phil Traill', 1),
 ('Christian Alvart', 1),
 ('Michael Spierig', 1),
 ('Peter Spierig', 1),
 ('Brandon Camp', 1),
 ('Rajkumar Hirani', 1),
 ('Grant Heslov', 1),
 ('Jorge Blanco', 1),
 ('Javier Abad', 1),
 ('Marcos MartÃ\xadnez', 1),
 ('Troy Duffy', 1),
 ('John Schultz', 1),
 ('Olatunde Osunsanmi', 1),
 ('Mike Judge', 1),
 ('Daniel Barber', 1),
 ('Steve Shill', 1),
 ('Jonas Elmer', 1),
 ('Stewart Hendler', 1),
 ('Toby Wilkins', 1),
 ('Nathan Greno', 1),
 ('Florian Henckel von Donnersmarck', 1),
 ('Ethan Maniquis', 1),
 ('Ryan Murphy', 1),
 ('Anand Tucker', 1),
 ('Alan Poul', 1),
 ('Josh Gordon', 1),
 ('Will Speck', 1),
 ('Troy Nixey', 1),
 ('Samuel Bayer', 1),
 ('Susanna White', 1),
 ('Steve Antin', 1),
 ('Nanette Burstein', 1),
 ('Greg Berlanti', 1),
 ('Colin Strause', 1),
 ('Greg Strause', 1),
 ('Jim Field Smith', 1),
 ('Anthony Bell', 1),
 ('Ben Gluck', 1),
 ('David Lynch', 1),
 ('Sharon Maguire', 1),
 ('Gary Trousdale', 1),
 ('Kirk Wise', 1),
 ('J.B. Rogers', 1),
 ('Ted Demme', 1),
 ('Jean-Jacques Annaud', 1),
 ('Joel Gallen', 1),
 ('Alejandro AmenÃ¡bar', 1),
 ('Lawrence Guterman', 1),
 ('Chris Nahon', 1),
 ('Jerry Zucker', 1),
 ('Robert Altman', 1),
 ('James Isaac', 1),
 ('John Dahl', 1),
 ('Simon Wincer', 1),
 ('Bill Paxton', 1),
 ('Dennie Gordon', 1),
 ('John Boorman', 1),
 ("Pat O'Connor", 1),
 ('Gregory Poirier', 1),
 ('Rob Pritts', 1),
 ('Francine McDougall', 1),
 ('DJ Pooh', 1),
 ('Pierre Morel', 1),
 ('John Stevenson', 1),
 ('Loveleen Tandan', 1),
 ('Tom Vaughan', 1),
 ('Mark Herman', 1),
 ('Jeff Wadlow', 1),
 ('Pete Travis', 1),
 ('David Wain', 1),
 ('Peter Sollett', 1),
 ('Fred Wolf', 1),
 ('David Hackl', 1),
 ('Jon Avnet', 1),
 ('Bryan Bertino', 1),
 ('Chris Carter', 1),
 ('John Patrick Shanley', 1),
 ('Paul Weiland', 1),
 ('David Moreau', 1),
 ('Xavier Palud', 1),
 ('Michael McCullers', 1),
 ('Howard Deutch', 1),
 ('Jennifer Flackett', 1),
 ('Mark Levin', 1),
 ('Anthony Leondis', 1),
 ('Nicolas Winding Refn', 1),
 ('Jennifer Yuh', 1),
 ('Brad Lewis', 1),
 ('Terrence Malick', 1),
 ('Michel Hazanavicius', 1),
 ('George Nolfi', 1),
 ('Tom Hanks', 1),
 ('Mark Mylod', 1),
 ('Chris Gorak', 1),
 ('Tate Taylor', 1),
 ('Christian E. Christiansen', 1),
 ('Oliver Parker', 1),
 ('Daniel Barnz', 1),
 ('Todd Strauss-Schulson', 1),
 ('Gonzalo LÃ³pez-Gallego', 1),
 ('John Michael McDonagh', 1),
 ('Jesse Peretz', 1),
 ('Jason Winer', 1),
 ('Alister Grierson', 1),
 ('Douglas McGrath', 1),
 ('Sean McNamara', 1),
 ('Joe Nussbaum', 1),
 ('Benny Chan', 1),
 ('Corey Yuen Kwai', 1),
 ('Curtis Hanson', 1),
 ('Joel Zwick', 1),
 ('Stuart Baird', 1),
 ('Steve Beck', 1),
 ('Lorna Cook', 1),
 ('Chuck Russell', 1),
 ('Julie Taymor', 1),
 ('Barbet Schroeder', 1),
 ('Simon Wells', 1),
 ('Adrian Lyne', 1),
 ('Michael Rymer', 1),
 ('Marcus Raboy', 1),
 ('Robin Budd', 1),
 ('Donovan Cook', 1),
 ('Mark Romanek', 1),
 ('Mark Pellington', 1),
 ('Jonathan Frakes', 1),
 ('Rick Rosenthal', 1),
 ('Tamra Davis', 1),
 ('Charles Stone III', 1),
 ('Kevin Bray', 1),
 ('MÃ¥ns MÃ¥rlind', 1),
 ('BjÃ¶rn Stein', 1),
 ('Mark Andrews', 1),
 ('Steve Purcell', 1),
 ('Brenda Chapman', 1),
 ('Rupert Sanders', 1),
 ('Mike Thurmeier', 1),
 ('Juan Antonio Bayona', 1),
 ('Rich Moore', 1),
 ('Stephen Chbosky', 1),
 ('Drew Goddard', 1),
 ('Peter Ramsey', 1),
 ('Michael Sucsy', 1),
 ('Rian Johnson', 1),
 ('Scott Speer', 1),
 ('Mike McCoy', 1),
 ('Nima Nourizadeh', 1),
 ('John Hillcoat', 1),
 ('Jeff Newitt', 1),
 ('Stephen St. Leger', 1),
 ('James Mather', 1),
 ('James Watkins', 1),
 ('Daniel Espinosa', 1),
 ('Asger Leth', 1),
 ('John Gulager', 1),
 ('Ole Bornedal', 1),
 ('Michael J. Bassett', 1),
 ('Andrew Dominik', 1),
 ('Nicholas Jarecki', 1),
 ('Dustin Hoffman', 1),
 ('Sam Fell', 1),
 ('Chris Butler', 1),
 ('Brian Klugman', 1),
 ('Lee Sternthal', 1),
 ('Dan Cutforth', 1),
 ('Jane Lipsitz', 1),
 ('Tom Shadyac', 1),
 ('Richard Curtis', 1),
 ('Stephen Norrington', 1),
 ('Steve Trenbirth', 1),
 ('Terry Zwigoff', 1),
 ('Peter Howitt', 1),
 ('Jan de Bont', 1),
 ('Rob Schmidt', 1),
 ('Peter Weir', 1),
 ('Jon Amiel', 1),
 ('Charles Herman-Wurmfeld', 1),
 ('Anthony Minghella', 1),
 ('Ronny Yu', 1),
 ('Kevin Costner', 1),
 ('Jim Fall', 1),
 ('Lawrence Kasdan', 1),
 ('Patty Jenkins', 1),
 ('Troy Miller', 1),
 ('Uwe Boll', 1),
 ('Mike Tollin', 1),
 ('FranÃ§ois Ozon', 1),
 ('Christopher Guest', 1),
 ('Christine Jeffs', 1),
 ('Jennifer Lee', 1),
 ('Shane Black', 1),
 ('Steve McQueen', 1),
 ('Dan Scanlon', 1),
 ('Tommy Wirkola', 1),
 ('Jean-Marc VallÃ©e', 1),
 ('Klay Hall', 1),
 ('Harmony Korine', 1),
 ('Fede Alvarez', 1),
 ('Derek Cianfrance', 1),
 ('Kimberly Peirce', 1),
 ('John Carney', 1),
 ('Ken Scott', 1),
 ('Seth Rogen', 1),
 ('Evan Goldberg', 1),
 ('Mike Flanagan', 1),
 ('David Soren', 1),
 ('Andy Muschietti', 1),
 ('Rusty Cundieff', 1),
 ('James Duffy', 1),
 ('Griffin Dunne', 1),
 ('Patrik Forsberg', 1),
 ('Will Graham', 1),
 ('Jonathan van Tulleken', 1),
 ('Scott Moore', 1),
 ('Jon Lucas', 1),
 ('Callan Brunker', 1),
 ('Amma Asante', 1),
 ('Cody Cameron', 1),
 ('Kris Pearn', 1),
 ('Giuseppe Tornatore', 1),
 ('Jeff Nichols', 1),
 ('Jonathan Teplitzky', 1),
 ('Neil Nightingale', 1),
 ('Barry Cook', 1),
 ('Ric Roman Waugh', 1),
 ('David E. Talbert', 1),
 ('Christopher B. Landon', 1),
 ('Joshua Michael Stern', 1),
 ('Anthony Silverston', 1),
 ('Ed Gass-Donnelly', 1),
 ('Oliver Hirschbiegel', 1),
 ('Fyodor Bondarchuk', 1),
 ('Frank Miller', 1),
 ('Garth Jennings', 1),
 ('Rob Bowman', 1),
 ('Mike Johnson', 1),
 ('Steve Box', 1),
 ('Angela Robinson', 1),
 ('Cory Edwards', 1),
 ('Todd Edwards', 1),
 ('Tony Leech', 1),
 ('John Polson', 1),
 ('Sydney Pollack', 1),
 ('Terry Gilliam', 1),
 ('Florent-Emilio Siri', 1),
 ('Jay Chandrasekhar', 1),
 ('Stephen Gaghan', 1),
 ('Frederik Du Chau', 1),
 ('Andrew Douglas', 1),
 ('Dean Parisot', 1),
 ('Jean-FranÃ§ois Richet', 1),
 ('Jim Jarmusch', 1),
 ('George A. Romero', 1),
 ('Rupert Wainwright', 1),
 ('Clare Kilner', 1),
 ('Richard Shepard', 1),
 ('Fernando Meirelles', 1),
 ('Geoffrey Sax', 1),
 ('Stephen Kay', 1),
 ('Joe Ranft', 1),
 ('Spike Lee', 1),
 ('Karey Kirkpatrick', 1),
 ('Frank Marshall', 1),
 ('Christophe Gans', 1),
 ('Stefen Fangmeier', 1),
 ('Alejandro Agresti', 1),
 ("Matthew O'Callaghan", 1),
 ('Jared Hess', 1),
 ('Jonathan Dayton', 1),
 ('Valerie Faris', 1),
 ('Greg Coolidge', 1),
 ('Roger Allers', 1),
 ('Jill Culton', 1),
 ('Steve Oedekerk', 1),
 ('Chris Noonan', 1),
 ('John Bonito', 1),
 ('Liz Friedlander', 1),
 ('Elizabeth Allen Rosenbaum', 1),
 ('Richard Donner', 1),
 ('Richard Eyre', 1),
 ('Barry Levinson', 1),
 ('Renny Harlin', 1),
 ('Sanjay Gadhvi', 1),
 ('Glen Morgan', 1),
 ('Phil Joanou', 1),
 ('Mira Nair', 1),
 ('Rachid Bouchareb', 1),
 ('William Brent Bell', 1),
 ('Doug Atchison', 1),
 ('Eric Bress', 1),
 ('J. Mackye Gruber', 1),
 ('Alexander Witt', 1),
 ('Brad Silberling', 1),
 ('Peter Hewitt', 1),
 ('Bibo Bergeron', 1),
 ('Stephen Hillenburg', 1),
 ('Mark Rosman', 1),
 ('Rawson Marshall Thurber', 1),
 ('Jonathan Hensleigh', 1),
 ('David Koepp', 1),
 ('Don Mancini', 1),
 ('Terry George', 1),
 ('Trey Parker', 1),
 ('Sara Sugarman', 1),
 ('Guy Ferland', 1),
 ('Joseph Ruben', 1),
 ('Nick Hamm', 1),
 ('Joseph Kahn', 1),
 ("Gavin O'Connor", 1),
 ('Kevin Allen', 1),
 ('Christopher Erskin', 1),
 ('Jan Pinkava', 1),
 ('Frank Darabont', 1),
 ('Sean Penn', 1),
 ('GÃ¡bor CsupÃ³', 1),
 ('Paul Thomas Anderson', 1),
 ('Raman Hui', 1),
 ('Steve Hickner', 1),
 ('Stephen J. Anderson', 1),
 ('Kevin Munroe', 1),
 ('Juan Carlos Fresnadillo', 1),
 ('Steve Bendelack', 1),
 ('Bruce A. Evans', 1),
 ('Robert Redford', 1),
 ('Kirsten Sheridan', 1),
 ('Philip G. Atwell', 1),
 ('Mennan Yapo', 1),
 ('Scott Hicks', 1),
 ('Ash Brannon', 1),
 ('Xavier Gens', 1),
 ('David Schwimmer', 1),
 ('Eli Roth', 1),
 ('Dave Meyers', 1),
 ('Julian Jarrold', 1),
 ('Shekhar Kapur', 1),
 ('Sidney Lumet', 1),
 ('Fred Savage', 1),
 ('Russell Mulcahy', 1),
 ('Michael Winterbottom', 1),
 ('Stephen Hopkins', 1),
 ('James Foley', 1),
 ('Mark Helfrich', 1),
 ('Jon Kasdan', 1),
 ('Shari Springer Berman', 1),
 ('Robert Pulcini', 1),
 ('James Gray', 1),
 ('Peter Hedges', 1),
 ('Alastair Fothergill', 1),
 ('Mark Linfield', 1),
 ('Wong Kar-wai', 1),
 ('Sylvain White', 1),
 ('Chris Rock', 1),
 ('Peter Webber', 1),
 ('Feng Xiaogang', 1),
 ('Ben Garant', 1),
 ('Ralph Zondag', 1),
 ('Eric Leighton', 1),
 ('David McNally', 1),
 ('Ben Younger', 1),
 ('Gregory Hoblit', 1),
 ('Mimi Leder', 1),
 ('Paul Verhoeven', 1),
 ('Mary Harron', 1),
 ('Lars von Trier', 1),
 ('Roger Spottiswoode', 1),
 ('Jonathan Lynn', 1),
 ('William Friedkin', 1),
 ('Robert Iscove', 1),
 ('Edward Norton', 1),
 ('Bonnie Hunt', 1)]

# 14. Кто из режиссеров снял больше всего Прибыльных фильмов?
Варианты ответов:
1. Steven Soderbergh
2. Clint Eastwood
3. Steven Spielberg
4. Ridley Scott
5. Christopher Nolan

In [50]:
answer_ls.append(4)
data=data[data['profit']>0]
data['director'].value_counts()

Ridley Scott              12
Steven Spielberg          10
Clint Eastwood            10
Steven Soderbergh         10
Shawn Levy                 9
                          ..
Mark Mylod                 1
Chris Weitz|Paul Weitz     1
Sarah Gavron               1
Anthony Minghella          1
Morten Tyldum              1
Name: director, Length: 774, dtype: int64

# 15. Кто из режиссеров принес больше всего прибыли?
Варианты ответов:
1. Steven Spielberg
2. Christopher Nolan
3. David Yates
4. James Cameron
5. Peter Jackson

In [51]:
answer_ls.append(5)
data['profit'] = data['revenue'] - data['budget']
data.groupby(['director'])['profit'].sum().sort_values(ascending = False)

director
Peter Jackson        5202593685
David Yates          3379295625
Christopher Nolan    3162548502
J.J. Abrams          2839169916
Michael Bay          2760938960
                        ...
John Bonito             2165608
Joe Nussbaum            2130000
Bill Paxton             2110448
Sarah Gavron            2002420
Christian Alvart        2000000
Name: profit, Length: 774, dtype: int64

# 16. Какой актер принес больше всего прибыли?
Варианты ответов:
1. Emma Watson
2. Johnny Depp
3. Michelle Rodriguez
4. Orlando Bloom
5. Rupert Grint

In [52]:
answer_ls.append(1)
df_cast = pd.DataFrame(data.cast.str.split('|').tolist()).stack().reset_index()
df_cast.columns = ['row_index','row2','cast']
df_cast['profit_cast'] = df_cast.row_index.apply(lambda x : data.iloc[x]['profit'])
df_cast['year'] = df_cast.row_index.apply(lambda x : data.iloc[x]['release_year'])
df_cast.groupby('cast')['profit_cast'].sum().sort_values(ascending = False)

cast
Emma Watson            6675368452
Daniel Radcliffe       6523915983
Rupert Grint           6413185247
Ian McKellen           6171916461
Robert Downey Jr.      5361847918
                          ...
Michelle Yeoh             2108608
MÃ©lanie Thierry          2108608
Lambert Wilson            2108608
Callum Keith Rennie       2000000
Kerry O'Malley            2000000
Name: profit_cast, Length: 2922, dtype: int64

# 17. Какой актер принес меньше всего прибыли в 2012 году?
Варианты ответов:
1. Nicolas Cage
2. Danny Huston
3. Kirsten Dunst
4. Jim Sturgess
5. Sami Gayle

In [53]:
answer_ls.append(3)
df_cast = pd.DataFrame(data.cast.str.split('|').tolist()).stack().reset_index()
df_cast.columns = ['row_index','row2','cast']
df_cast['profit_cast'] = df_cast.row_index.apply(lambda x : data.iloc[x]['profit'])
df_cast['year'] = df_cast.row_index.apply(lambda x : data.iloc[x]['release_year'])
df_cast.query('year == 2012').groupby('cast')['profit_cast'].sum().sort_values(ascending = False)

cast
Chris Hemsworth         1562643990
Denis Leary             1319460639
Mark Ruffalo            1299557910
Chris Evans             1299557910
Robert Downey Jr.       1299557910
                           ...
Matt Bush                  3493728
Jean-Luc Bilodeau          3493728
Benicio del Toro           2000000
Blake Lively               2000000
Aaron Taylor-Johnson       2000000
Name: profit_cast, Length: 373, dtype: int64

# 18. Какой актер снялся в большем количестве высокобюджетных фильмов? (в фильмах где бюджет выше среднего по данной выборке)
Варианты ответов:
1. Tom Cruise
2. Mark Wahlberg 
3. Matt Damon
4. Angelina Jolie
5. Adam Sandler

In [30]:
answer_ls.append(3)
data=data[data['budget']>budget.mean()]
cast_counter = Counter()
for x in data.cast.str.split('|'):
    cast_counter += Counter(x)
cast_counter.most_common()

[('Matt Damon', 18),
 ('Adam Sandler', 17),
 ('Angelina Jolie', 16),
 ('Tom Cruise', 15),
 ('Samuel L. Jackson', 15),
 ('Eddie Murphy', 15),
 ('Mark Wahlberg', 14),
 ('Hugh Jackman', 14),
 ('Ben Stiller', 14),
 ('Jamie Foxx', 14),
 ('Russell Crowe', 14),
 ('Johnny Depp', 13),
 ('Jude Law', 13),
 ('Bruce Willis', 13),
 ('Will Smith', 13),
 ('Dwayne Johnson', 12),
 ('Ian McKellen', 12),
 ('Brad Pitt', 12),
 ('Owen Wilson', 12),
 ('Cameron Diaz', 12),
 ('Nicolas Cage', 12),
 ('Robert De Niro', 12),
 ('Leonardo DiCaprio', 11),
 ('Daniel Craig', 11),
 ('Robert Downey Jr.', 11),
 ('Steve Buscemi', 11),
 ('Vin Diesel', 10),
 ('Mark Ruffalo', 10),
 ('Jack Black', 10),
 ('Denzel Washington', 10),
 ('Emma Watson', 10),
 ('Gary Oldman', 10),
 ('Tom Hanks', 10),
 ('Orlando Bloom', 10),
 ('Ralph Fiennes', 9),
 ('Cate Blanchett', 9),
 ('Michael Caine', 9),
 ('Ewan McGregor', 9),
 ('Paul Bettany', 9),
 ('Brendan Gleeson', 9),
 ('Shia LaBeouf', 9),
 ('Nicole Kidman', 9),
 ('Colin Farrell', 9),
 ('Rachel Weisz', 9),
 ('Halle Berry', 9),
 ('Charlize Theron', 8),
 ('Kevin James', 8),
 ('Chris Hemsworth', 8),
 ('Helena Bonham Carter', 8),
 ('Josh Hutcherson', 8),
 ('George Clooney', 8),
 ('James Franco', 8),
 ('Christian Bale', 8),
 ('Gerard Butler', 8),
 ('Sylvester Stallone', 8),
 ('Rosario Dawson', 8),
 ('Ben Kingsley', 8),
 ('Bill Nighy', 8),
 ('Daniel Radcliffe', 8),
 ('Rupert Grint', 8),
 ('Jim Carrey', 8),
 ('Vince Vaughn', 8),
 ('Alec Baldwin', 8),
 ('Steve Carell', 8),
 ('Harrison Ford', 7),
 ('Jason Statham', 7),
 ('Chris Evans', 7),
 ('Woody Harrelson', 7),
 ('Josh Brolin', 7),
 ('Jeff Bridges', 7),
 ('Anne Hathaway', 7),
 ('Patrick Stewart', 7),
 ('Jennifer Connelly', 7),
 ('Anthony Hopkins', 7),
 ('Morgan Freeman', 7),
 ('Billy Crudup', 7),
 ('Jason Lee', 7),
 ('Jessica Biel', 7),
 ('Julia Roberts', 7),
 ('Ryan Reynolds', 7),
 ('Liam Neeson', 7),
 ('Karl Urban', 7),
 ('Richard Jenkins', 7),
 ('Chris Rock', 7),
 ('Kate Winslet', 6),
 ('Paul Walker', 6),
 ('Arnold Schwarzenegger', 6),
 ('Sean Bean', 6),
 ('Scarlett Johansson', 6),
 ('Elizabeth Banks', 6),
 ('Ving Rhames', 6),
 ('Mark Strong', 6),
 ('Jeffrey Wright', 6),
 ('Gwyneth Paltrow', 6),
 ('Matthew McConaughey', 6),
 ('Rosamund Pike', 6),
 ('Logan Lerman', 6),
 ('Robin Williams', 6),
 ('Stanley Tucci', 6),
 ('Mel Gibson', 6),
 ('Kevin Costner', 6),
 ('John Goodman', 6),
 ('Aaron Eckhart', 6),
 ('Justin Long', 6),
 ('Will Ferrell', 6),
 ('Seann William Scott', 6),
 ('Paul Giamatti', 6),
 ('Dustin Hoffman', 6),
 ('Mike Myers', 6),
 ('Eva Mendes', 6),
 ('Kate Beckinsale', 6),
 ('Jon Voight', 6),
 ('Jackie Chan', 6),
 ('Tobey Maguire', 6),
 ('Keanu Reeves', 6),
 ('Guy Pearce', 6),
 ('John Leguizamo', 6),
 ('Tommy Lee Jones', 6),
 ('Michelle Rodriguez', 5),
 ('Michael PeÃ±a', 5),
 ('Paul Rudd', 5),
 ('Jennifer Lawrence', 5),
 ('Carla Gugino', 5),
 ('Ioan Gruffudd', 5),
 ('Simon Pegg', 5),
 ('Giovanni Ribisi', 5),
 ('Frances McDormand', 5),
 ('Elijah Wood', 5),
 ('Jake Gyllenhaal', 5),
 ('Sam Worthington', 5),
 ('Delroy Lindo', 5),
 ('Bradley Cooper', 5),
 ('Donald Sutherland', 5),
 ('Ben Affleck', 5),
 ('Andy Serkis', 5),
 ('John Turturro', 5),
 ('Jonah Hill', 5),
 ('Julianne Moore', 5),
 ('John Malkovich', 5),
 ('Ian McShane', 5),
 ('Chris Pine', 5),
 ('Keira Knightley', 5),
 ('Jessica Alba', 5),
 ('Eric Bana', 5),
 ('Benjamin Bratt', 5),
 ('Hank Azaria', 5),
 ('John Travolta', 5),
 ('David Cross', 5),
 ('Clive Owen', 5),
 ('Sam Elliott', 5),
 ('Don Cheadle', 5),
 ('Ron Perlman', 5),
 ('Antonio Banderas', 5),
 ('Peter Sarsgaard', 5),
 ('Zach Galifianakis', 5),
 ('Nick Nolte', 5),
 ('Geoffrey Rush', 5),
 ('Brendan Fraser', 5),
 ('Jennifer Aniston', 5),
 ('Edward Norton', 5),
 ('Judi Dench', 5),
 ('John C. Reilly', 5),
 ('Sacha Baron Cohen', 5),
 ('Kirsten Dunst', 5),
 ('Djimon Hounsou', 5),
 ('Catherine Zeta-Jones', 5),
 ('Tom Hardy', 4),
 ('Kristen Wiig', 4),
 ('Christoph Waltz', 4),
 ('Michelle Monaghan', 4),
 ('Liam Hemsworth', 4),
 ('Amanda Seyfried', 4),
 ('Steve Martin', 4),
 ('Ray Winstone', 4),
 ('Rose Byrne', 4),
 ('Tom Hiddleston', 4),
 ('Michael Fassbender', 4),
 ('Megan Fox', 4),
 ('Will Arnett', 4),
 ('William Fichtner', 4),
 ('Marton Csokas', 4),
 ('Emma Stone', 4),
 ('Bill Paxton', 4),
 ('Joel Edgerton', 4),
 ('Bryan Cranston', 4),
 ('Jay Baruchel', 4),
 ('Eva Green', 4),
 ('David Wenham', 4),
 ('Michael Gambon', 4),
 ('Mickey Rourke', 4),
 ('Joseph Gordon-Levitt', 4),
 ('Bill Murray', 4),
 ('Carrie-Anne Moss', 4),
 ('Bruce Greenwood', 4),
 ('Patrick Wilson', 4),
 ('Chiwetel Ejiofor', 4),
 ('Thandie Newton', 4),
 ('Anna Faris', 4),
 ('Amy Adams', 4),
 ('Susan Sarandon', 4),
 ('PenÃ©lope Cruz', 4),
 ('Jon Favreau', 4),
 ('Luis GuzmÃ¡n', 4),
 ('Jason Bateman', 4),
 ('Seth Rogen', 4),
 ('Reese Witherspoon', 4),
 ('Tyrese Gibson', 4),
 ('Catherine Keener', 4),
 ('James Cromwell', 4),
 ('Julie Andrews', 4),
 ('Alfred Molina', 4),
 ('Salma Hayek', 4),
 ('Kristen Stewart', 4),
 ('Peter Facinelli', 4),
 ('Jason Isaacs', 4),
 ('Ashton Kutcher', 4),
 ('Jack Nicholson', 4),
 ('Viggo Mortensen', 4),
 ('Liv Tyler', 4),
 ('Ed Harris', 4),
 ('Heath Ledger', 4),
 ('Kurt Russell', 4),
 ('Angela Bassett', 4),
 ('TÃ©a Leoni', 4),
 ('Terrence Howard', 4),
 ('Hayden Christensen', 4),
 ('Terence Stamp', 4),
 ('Anthony Mackie', 4),
 ('Zooey Deschanel', 4),
 ('Matthew Broderick', 4),
 ('Ed Helms', 4),
 ('Hugo Weaving', 4),
 ('Natalie Portman', 4),
 ('Denis Leary', 4),
 ('Brian Cox', 4),
 ('Willem Dafoe', 4),
 ('Joaquin Phoenix', 4),
 ('Famke Janssen', 4),
 ('Peter Stormare', 4),
 ('Kerry Washington', 4),
 ('Billy Connolly', 4),
 ('Drew Barrymore', 4),
 ('RenÃ©e Zellweger', 4),
 ('Christopher Walken', 4),
 ('Bryce Dallas Howard', 3),
 ('Theo James', 3),
 ('Miles Teller', 3),
 ('Jason Clarke', 3),
 ('Jai Courtney', 3),
 ('Jessica Chastain', 3),
 ('Sandra Bullock', 3),
 ('Michael Keaton', 3),
 ('Bill Hader', 3),
 ('Monica Bellucci', 3),
 ('Mila Kunis', 3),
 ('Channing Tatum', 3),
 ('Josh Gad', 3),
 ('Michael Douglas', 3),
 ('Bobby Cannavale', 3),
 ('Hugh Laurie', 3),
 ('Alexandra Daddario', 3),
 ('Jeremy Renner', 3),
 ('Amy Ryan', 3),
 ('Henry Cavill', 3),
 ('Armie Hammer', 3),
 ('Kate Mara', 3),
 ('Jamie Bell', 3),
 ('Toby Kebbell', 3),
 ('Garrett Hedlund', 3),
 ('Andy Samberg', 3),
 ('Rachel McAdams', 3),
 ('Marion Cotillard', 3),
 ('Charlie Hunnam', 3),
 ('Casey Affleck', 3),
 ('Zoe Saldana', 3),
 ('Robert Redford', 3),
 ('Martin Freeman', 3),
 ('Richard Armitage', 3),
 ('Neil Patrick Harris', 3),
 ('James McAvoy', 3),
 ('Li Bingbing', 3),
 ('Colm Feore', 3),
 ('Sienna Miller', 3),
 ('Ken Watanabe', 3),
 ('Elle Fanning', 3),
 ('Sharlto Copley', 3),
 ('Luke Evans', 3),
 ('Dominic Cooper', 3),
 ('John Hurt', 3),
 ('Rufus Sewell', 3),
 ('Abbie Cornish', 3),
 ('Jesse Eisenberg', 3),
 ('Leslie Mann', 3),
 ('Andy GarcÃ\xada', 3),
 ('Emily Browning', 3),
 ('Miranda Otto', 3),
 ('William Hurt', 3),
 ('Stephen Lang', 3),
 ('Christopher Plummer', 3),
 ('Malin Ã…kerman', 3),
 ('Amanda Peet', 3),
 ('Stellan SkarsgÃ¥rd', 3),
 ('Dennis Quaid', 3),
 ('Dakota Fanning', 3),
 ('Kristen Bell', 3),
 ('Kiefer Sutherland', 3),
 ('Robin Wright', 3),
 ('Josh Duhamel', 3),
 ('Meryl Streep', 3),
 ('Olivia Wilde', 3),
 ('Freddie Highmore', 3),
 ('Jordana Brewster', 3),
 ('Radha Mitchell', 3),
 ('Liev Schreiber', 3),
 ('Danny Huston', 3),
 ('Hugh Grant', 3),
 ('Sarah Jessica Parker', 3),
 ('Mary Steenburgen', 3),
 ('Russell Brand', 3),
 ('Emily Mortimer', 3),
 ('Skandar Keynes', 3),
 ('Georgie Henley', 3),
 ('Jason Flemyng', 3),
 ('Mary Elizabeth Winstead', 3),
 ('Brandon T. Jackson', 3),
 ('Mary-Louise Parker', 3),
 ('Maria Bello', 3),
 ('Robert Pattinson', 3),
 ('Taylor Lautner', 3),
 ('Greg Kinnear', 3),
 ('Kristin Davis', 3),
 ('Chris Noth', 3),
 ('James Marsden', 3),
 ('Dan Aykroyd', 3),
 ('Milla Jovovich', 3),
 ('Cuba Gooding Jr.', 3),
 ('Michael Clarke Duncan', 3),
 ('James Gandolfini', 3),
 ('Laurence Fishburne', 3),
 ('Billy Bob Thornton', 3),
 ('Teri Polo', 3),
 ('Lucy Liu', 3),
 ('Jada Pinkett Smith', 3),
 ('David Schwimmer', 3),
 ('Jeffrey Tambor', 3),
 ('Thomas Kretschmann', 3),
 ('Kenneth Branagh', 3),
 ('Cliff Curtis', 3),
 ('Michael Chiklis', 3),
 ('Jaden Smith', 3),
 ('Sienna Guillory', 3),
 ('Al Pacino', 3),
 ('Spencer Breslin', 3),
 ('Paula Patton', 3),
 ('Tim Robbins', 3),
 ('Justin Bartha', 3),
 ('Ken Jeong', 3),
 ('Jane Lynch', 3),
 ('Isla Fisher', 3),
 ('CiarÃ¡n Hinds', 3),
 ('Lily Collins', 3),
 ('Kevin Bacon', 3),
 ('Ray Romano', 3),
 ('Chris Cooper', 3),
 ('Emma Thompson', 3),
 ('William Shatner', 3),
 ('Cole Hauser', 3),
 ('Randy Quaid', 3),
 ('Harvey Keitel', 3),
 ('Scott Glenn', 3),
 ('David Oyelowo', 3),
 ('Michelle Pfeiffer', 3),
 ('David Spade', 3),
 ('Marisa Tomei', 3),
 ('Josh Lucas', 3),
 ('David Thewlis', 3),
 ('Connie Nielsen', 3),
 ('Bruce McGill', 3),
 ('Shirley MacLaine', 3),
 ('Hiroyuki Sanada', 3),
 ('Sean Penn', 3),
 ('Richard Roxburgh', 3),
 ('Val Kilmer', 3),
 ('Emmy Rossum', 3),
 ('Miranda Richardson', 3),
 ('Chris Pratt', 2),
 ('Irrfan Khan', 2),
 ('Nicholas Hoult', 2),
 ('Shailene Woodley', 2),
 ('Domhnall Gleeson', 2),
 ('J.K. Simmons', 2),
 ('Jeff Daniels', 2),
 ('Allison Janney', 2),
 ('Steve Coogan', 2),
 ('Amy Poehler', 2),
 ('LÃ©a Seydoux', 2),
 ('Evangeline Lilly', 2),
 ('Corey Stoll', 2),
 ('Colin Firth', 2),
 ('Giancarlo Esposito', 2),
 ('Alicia Vikander', 2),
 ('Elizabeth Debicki', 2),
 ('Rihanna', 2),
 ('Jennifer Lopez', 2),
 ('Edgar RamÃ\xadrez', 2),
 ('Teresa Palmer', 2),
 ('Viola Davis', 2),
 ('Benjamin Walker', 2),
 ('Ben Whishaw', 2),
 ('Rooney Mara', 2),
 ('Selena Gomez', 2),
 ('Mia Wasikowska', 2),
 ('Sebastian Stan', 2),
 ('Ken Stott', 2),
 ('Graham McTavish', 2),
 ('Jamie Chung', 2),
 ('Rami Malek', 2),
 ('Ray Stevenson', 2),
 ('Nicola Peltz', 2),
 ('Keri Russell', 2),
 ('ChloÃ« Grace Moretz', 2),
 ('Andrew Garfield', 2),
 ('Emily Blunt', 2),
 ('Aaron Paul', 2),
 ('Ben Barnes', 2),
 ('Kit Harington', 2),
 ('Lena Headey', 2),
 ('Joel Kinnaman', 2),
 ('Jackie Earle Haley', 2),
 ('Adewale Akinnuoye-Agbaje', 2),
 ('RamÃ³n RodrÃ\xadguez', 2),
 ('Yvonne Strahovski', 2),
 ('Kellan Lutz', 2),
 ('Sigourney Weaver', 2),
 ('MÃ©lanie Laurent', 2),
 ('Julie Walters', 2),
 ('Zachary Quinto', 2),
 ('Anton Yelchin', 2),
 ('Eddie Marsan', 2),
 ('Jeffrey Dean Morgan', 2),
 ('John Cusack', 2),
 ('Oliver Platt', 2),
 ('Keith David', 2),
 ('Marlon Wayans', 2),
 ('James Caan', 2),
 ('Saoirse Ronan', 2),
 ('Sam Rockwell', 2),
 ('Tracy Morgan', 2),
 ('Zachary Levi', 2),
 ('Mary Kay Place', 2),
 ('Michael Cera', 2),
 ('Oscar Isaac', 2),
 ('Lynn Collins', 2),
 ('Jason Segel', 2),
 ('Dolph Lundgren', 2),
 ('Michelle Williams', 2),
 ('Mandy Moore', 2),
 ('Tim Allen', 2),
 ('Ned Beatty', 2),
 ('Joan Cusack', 2),
 ('Timothy Dalton', 2),
 ('Gemma Arterton', 2),
 ('Anna Kendrick', 2),
 ('Barbra Streisand', 2),
 ('Helen Mirren', 2),
 ('Tina Fey', 2),
 ('Ashley Greene', 2),
 ('Jordi MollÃ\xa0', 2),
 ('Javier Bardem', 2),
 ('Katherine Heigl', 2),
 ('Tom Selleck', 2),
 ('Cynthia Nixon', 2),
 ('Kim Cattrall', 2),
 ('Essie Davis', 2),
 ('Eric Dane', 2),
 ('Cam Gigandet', 2),
 ('Julianne Hough', 2),
 ('Stephanie Szostak', 2),
 ('Bette Midler', 2),
 ('Carey Mulligan', 2),
 ('Justin Timberlake', 2),
 ('John Cleese', 2),
 ('Billy Crystal', 2),
 ("Frances O'Connor", 2),
 ('John Lithgow', 2),
 ('Josh Hartnett', 2),
 ('John Hannah', 2),
 ('Arnold Vosloo', 2),
 ('Michael J. Fox', 2),
 ('James Garner', 2),
 ('Noah Taylor', 2),
 ('Tim Roth', 2),
 ('Kris Kristofferson', 2),
 ('Tom Sizemore', 2),
 ('Chris Tucker', 2),
 ('Zhang Ziyi', 2),
 ('Ernie Reyes, Jr.', 2),
 ('Elizabeth Perkins', 2),
 ('Sam Shepard', 2),
 ('Dylan Baker', 2),
 ('Gene Hackman', 2),
 ('Dominic West', 2),
 ('Edward Burns', 2),
 ('Martin Landau', 2),
 ('David Ogden Stiers', 2),
 ('Courteney Cox', 2),
 ('David Hyde Pierce', 2),
 ('Til Schweiger', 2),
 ('David Andrews', 2),
 ('William H. Macy', 2),
 ('Jeff Garlin', 2),
 ('Olga Kurylenko', 2),
 ('Jet Li', 2),
 ('Selma Blair', 2),
 ('Michael Rooker', 2),
 ('William Moseley', 2),
 ('Anna Popplewell', 2),
 ('Kathy Bates', 2),
 ('Michael Ealy', 2),
 ('Malcolm McDowell', 2),
 ('Alan Arkin', 2),
 ('Ali Suliman', 2),
 ('Adam Scott', 2),
 ('Kate Hudson', 2),
 ('Ewen Bremner', 2),
 ('Lambert Wilson', 2),
 ('Charlotte Rampling', 2),
 ('Robert Duvall', 2),
 ('Christina Ricci', 2),
 ('Matthew Fox', 2),
 ('Gabriel Macht', 2),
 ('Paz Vega', 2),
 ('Kevin Kline', 2),
 ('Gabrielle Union', 2),
 ('Goran Visnjic', 2),
 ('Bailee Madison', 2),
 ('Noomi Rapace', 2),
 ('Larry the Cable Guy', 2),
 ('Eddie Izzard', 2),
 ('Vanessa Hudgens', 2),
 ('Emily Watson', 2),
 ('Asa Butterfield', 2),
 ('Dominic Purcell', 2),
 ('Maggie Q', 2),
 ('Isabel Lucas', 2),
 ('Katie Holmes', 2),
 ('Amy Sedaris', 2),
 ('Jason Momoa', 2),
 ('Lea Michele', 2),
 ('Johnny A. Sanchez', 2),
 ('Seth Green', 2),
 ('Queen Latifah', 2),
 ('Richard Harris', 2),
 ('Franka Potente', 2),
 ('Ian McDiarmid', 2),
 ('Max von Sydow', 2),
 ('Abigail Breslin', 2),
 ('Elias Koteas', 2),
 ('Liam Aiken', 2),
 ('Paul Newman', 2),
 ('BeyoncÃ© Knowles', 2),
 ('Mark Addy', 2),
 ('Adam Beach', 2),
 ('Izabella Scorupco', 2),
 ('Naomie Harris', 2),
 ('Idris Elba', 2),
 ('Martin Sheen', 2),
 ('Kevin McKidd', 2),
 ('Jim Broadbent', 2),
 ('Jim Sturgess', 2),
 ('Jonny Lee Miller', 2),
 ('Timothy Spall', 2),
 ('Taylor Kitsch', 2),
 ('Tadanobu Asano', 2),
 ('Nathan Lane', 2),
 ('Jack Davenport', 2),
 ('Claire Danes', 2),
 ('Jennifer Garner', 2),
 ('Martin Lawrence', 2),
 ('TchÃ©ky Karyo', 2),
 ('Bernie Mac', 2),
 ('Robert Patrick', 2),
 ('Steve Zahn', 2),
 ('Timothy Olyphant', 2),
 ('Diane Lane', 2),
 ('Jodie Foster', 2),
 ('Alice Braga', 2),
 ('Diego Luna', 2),
 ('James Badge Dale', 2),
 ('Patton Oswalt', 2),
 ('Cloris Leachman', 2),
 ('Max Martini', 2),
 ('Maggie Gyllenhaal', 2),
 ('Sung Kang', 2),
 ('Sophie Okonedo', 2),
 ('Zach Braff', 2),
 ('Jim Belushi', 2),
 ('AnnaSophia Robb', 2),
 ('Julian McMahon', 2),
 ('Lauren Graham', 2),
 ('Gong Li', 2),
 ('Amber Valletta', 2),
 ('Jeremy Irons', 2),
 ('Adrien Brody', 2),
 ('Lucas Black', 2),
 ('Donal Logue', 2),
 ('Paddy Considine', 2),
 ('Bonnie Hunt', 2),
 ('Yvan Attal', 2),
 ('Mads Mikkelsen', 2),
 ('Jean Reno', 2),
 ('Philip Seymour Hoffman', 2),
 ('Jonathan Rhys Meyers', 2),
 ('David Strathairn', 2),
 ('Sharon Stone', 2),
 ('Jacinda Barrett', 2),
 ('Gary Sinise', 2),
 ('Danny Glover', 2),
 ('Julia Stiles', 2),
 ('Diane Kruger', 2),
 ('Chi McBride', 2),
 ('Jane Krakowski', 2),
 ('Glenn Close', 2),
 ('Patrick Warburton', 2),
 ('John Michael Higgins', 2),
 ('Helen Hunt', 2),
 ("Vincent D'Onofrio", 1),
 ('Nick Robinson', 1),
 ('Hugh Keays-Byrne', 1),
 ('Josh Helman', 1),
 ('Ansel Elgort', 1),
 ('Mark Hamill', 1),
 ('Carrie Fisher', 1),
 ('Adam Driver', 1),
 ('Daisy Ridley', 1),
 ('Will Poulter', 1),
 ('Paul Anderson', 1),
 ('Emilia Clarke', 1),
 ('Jon Hamm', 1),
 ('Phyllis Smith', 1),
 ('Richard Kind', 1),
 ('Lewis Black', 1),
 ('Eddie Redmayne', 1),
 ('Douglas Booth', 1),
 ('Peter Dinklage', 1),
 ('Lily James', 1),
 ('Richard Madden', 1),
 ('Holliday Grainger', 1),
 ('Britt Robertson', 1),
 ('Raffey Cassidy', 1),
 ('Thomas Robinson', 1),
 ('Archie Panjabi', 1),
 ('Rebecca Ferguson', 1),
 ('Seth MacFarlane', 1),
 ('Jessica Barth', 1),
 ('Taron Egerton', 1),
 ("Dylan O'Brien", 1),
 ('Kaya Scodelario', 1),
 ('Thomas Brodie-Sangster', 1),
 ('Aidan Gillen', 1),
 ('Dylan Minnette', 1),
 ('Odeya Rush', 1),
 ('Jillian Bell', 1),
 ('Raymond Ochoa', 1),
 ('Jack Bright', 1),
 ('Maleah Nipay-Padilla', 1),
 ('Rose Leslie', 1),
 ('Ã“lafur Darri Ã“lafsson', 1),
 ('Luca Calvani', 1),
 ('Jim Parsons', 1),
 ('Matt Jones', 1),
 ('John Hawkes', 1),
 ('Luke Bracey', 1),
 ('Olivia Munn', 1),
 ('Leehom Wang', 1),
 ('Tang Wei', 1),
 ('Holt McCallany', 1),
 ('Michael B. Jordan', 1),
 ('Melissa McCarthy', 1),
 ('Miranda Hart', 1),
 ('Cillian Murphy', 1),
 ('Levi Miller', 1),
 ('Noah Schnapp', 1),
 ('Bill Melendez', 1),
 ('Venus Schultheis', 1),
 ('Hadley Belle Miller', 1),
 ('Madisyn Shipman', 1),
 ('Jim Beaver', 1),
 ('Tom Kenny', 1),
 ('Bill Fagerbakke', 1),
 ('Rodger Bumpass', 1),
 ('Clancy Brown', 1),
 ('Carolyn Lawrence', 1),
 ('Dave Bautista', 1),
 ('Scott Adsit', 1),
 ('Ryan Potter', 1),
 ('Daniel Henney', 1),
 ('T.J. Miller', 1),
 ('Carrie Coon', 1),
 ('Tyler Perry', 1),
 ('Jon Bernthal', 1),
 ('Rebel Wilson', 1),
 ('Alan Ritchson', 1),
 ('Noel Fisher', 1),
 ('Jack Reynor', 1),
 ('Judy Greer', 1),
 ('David Harbour', 1),
 ('Haley Bennett', 1),
 ('Dane DeHaan', 1),
 ('Jonas Armstrong', 1),
 ('Kyle Gallner', 1),
 ('Cole Konis', 1),
 ('Ben Reed', 1),
 ('Ben Mendelsohn', 1),
 ('Aaron Taylor-Johnson', 1),
 ('Elizabeth Olsen', 1),
 ('Juliette Binoche', 1),
 ('Juno Temple', 1),
 ('Isobelle Molloy', 1),
 ('Craig Berry', 1),
 ('Alison Brie', 1),
 ('David Burrows', 1),
 ('Sarah Gadon', 1),
 ('Art Parkinson', 1),
 ('Charles Dance', 1),
 ('Tom McGrath', 1),
 ('Chris Miller', 1),
 ('Christopher Knights', 1),
 ('Conrad Vernon', 1),
 ('Sullivan Stapleton', 1),
 ('Callan Mulvey', 1),
 ('Peter Capaldi', 1),
 ('Imelda Staunton', 1),
 ('Aksel Hennie', 1),
 ('Nonso Anozie', 1),
 ('Gemma Chan', 1),
 ('Rebecca Hall', 1),
 ('Ty Burrell', 1),
 ('Max Charles', 1),
 ('Ariel Winter', 1),
 ('Ellie Kemper', 1),
 ("Jack O'Connell", 1),
 ('Takamasa Ishihara', 1),
 ('Finn Wittrock', 1),
 ('Jessica Lucas', 1),
 ('QuvenzhanÃ© Wallis', 1),
 ('Imogen Poots', 1),
 ('Isaac Hempstead Wright', 1),
 ('Dee Bradley Baker', 1),
 ('Steve Blum', 1),
 ('Jessica Brown Findlay', 1),
 ('Liam McIntyre', 1),
 ('Gaia Weiss', 1),
 ('Scott Adkins', 1),
 ('Roxanne McKee', 1),
 ('Eli Roth', 1),
 ('Tom Felton', 1),
 ('Ed Asner', 1),
 ('Jordan Nagai', 1),
 ('Bob Peterson', 1),
 ('Leonard Nimoy', 1),
 ('Moon Bloodgood', 1),
 ('Ayelet Zurer', 1),
 ('Pierfrancesco Favino', 1),
 ('Anika Noni Rose', 1),
 ('Bruno Campos', 1),
 ('Michael-Leon Wooley', 1),
 ('Jennifer Cody', 1),
 ('Mr. T', 1),
 ('Teri Hatcher', 1),
 ('Jennifer Saunders', 1),
 ('Dawn French', 1),
 ('Steve Valentine', 1),
 ('Daryl Sabara', 1),
 ('Sage Ryan', 1),
 ('Victor Gojcaj', 1),
 ('Matthew Gray Gubler', 1),
 ('Rainn Wilson', 1),
 ('Lake Bell', 1),
 ('Anna Friel', 1),
 ('Danny McBride', 1),
 ('Jorma Taccone', 1),
 ('Matt Lauer', 1),
 ('Tony Kgoroge', 1),
 ('Patrick Mofokeng', 1),
 ('Matt Stern', 1),
 ('Max Minghella', 1),
 ('Ashraf Barhom', 1),
 ('Michael Lonsdale', 1),
 ('John Ortiz', 1),
 ('Tom Wilkinson', 1),
 ('Lisa Roberts Gillan', 1),
 ('Nelsan Ellis', 1),
 ('Michael Bunin', 1),
 ('Natalia Klimas', 1),
 ('Ellen Page', 1),
 ('Crispin Glover', 1),
 ('Eric Roberts', 1),
 ('Randy Couture', 1),
 ('Craig Ferguson', 1),
 ('America Ferrera', 1),
 ('Bruce Boxleitner', 1),
 ('Yaya DaCosta', 1),
 ('Donna Murphy', 1),
 ('M.C. Gainey', 1),
 ('Daniel Olbrychski', 1),
 ('Gary Sweet', 1),
 ('Arthur Angel', 1),
 ('Steven Berkoff', 1),
 ('Steve Toussaint', 1),
 ('Kieran Culkin', 1),
 ('Jake Abel', 1),
 ('Ethan Suplee', 1),
 ('Kevin Corrigan', 1),
 ('Maya Rudolph', 1),
 ('Jennifer Beals', 1),
 ('Taraji P. Henson', 1),
 ('Jimmi Simpson', 1),
 ('Noah Ringer', 1),
 ('Jackson Rathbone', 1),
 ('Dev Patel', 1),
 ('Shaun Toub', 1),
 ("Chris O'Dowd", 1),
 ('Juliette Lewis', 1),
 ("Catherine O'Hara", 1),
 ('Alex Borstein', 1),
 ('Emily Barclay', 1),
 ('Deborra-Lee Furness', 1),
 ('Cher', 1),
 ('Christina Aguilera', 1),
 ('Jemaine Clement', 1),
 ('Christina Applegate', 1),
 ('Pascale Hutton', 1),
 ('Kathryn Hahn', 1),
 ('Frank Langella', 1),
 ('Tom Cavanagh', 1),
 ('Christine Taylor', 1),
 ('Shawn Roberts', 1),
 ("Denis O'Hare", 1),
 ('Kate Bosworth', 1),
 ('Jang Dong-gun', 1),
 ('Ti Lung', 1),
 ('Wentworth Miller', 1),
 ('Ali Larter', 1),
 ('Kim Coates', 1),
 ('Kacey Barnfield', 1),
 ('Robbie Coltrane', 1),
 ('Mary Gibbs', 1),
 ('James Coburn', 1),
 ('Haley Joel Osment', 1),
 ('Sam Robards', 1),
 ('Jake Thomas', 1),
 ('Vincent Cassel', 1),
 ('Oded Fehr', 1),
 ('Corey Burton', 1),
 ('Claudia Christian', 1),
 ('John Mahoney', 1),
 ('Iain Glen', 1),
 ('Joseph Fiennes', 1),
 ('Bob Hoskins', 1),
 ('Shannyn Sossamon', 1),
 ('Laura Fraser', 1),
 ('Roselyn SÃ¡nchez', 1),
 ('Jeff Goldblum', 1),
 ('Alexander Pollock', 1),
 ('Miriam Margolyes', 1),

# 19. В фильмах какого жанра больше всего снимался Nicolas Cage?  
Варианты ответа:
1. Drama
2. Action
3. Thriller
4. Adventure
5. Crime

In [20]:
answer_ls.append(2)
data_filter=data[data.cast.str.contains("Cage", na=False)]
pd.DataFrame(data_filter.genres.str.split('|').tolist()).stack().value_counts()

Action             17
Thriller           15
Drama              12
Crime              10
Fantasy             8
Adventure           7
Comedy              6
Science Fiction     4
Mystery             3
Animation           3
Family              3
History             2
War                 1
Romance             1
Horror              1
dtype: int64

# 20. Какая студия сняла больше всего фильмов?
Варианты ответа:
1. Universal Pictures (Universal)
2. Paramount Pictures
3. Columbia Pictures
4. Warner Bros
5. Twentieth Century Fox Film Corporation

In [21]:
answer_ls.append(1)
pd.DataFrame(data.production_companies.str.split('|').tolist()).stack().value_counts()

Universal Pictures                        173
Warner Bros.                              168
Paramount Pictures                        122
Columbia Pictures                         117
Twentieth Century Fox Film Corporation    109
                                         ...
Head Gear Films                             1
Stoney Lake Entertainment                   1
Silver Bullet Productions (II)              1
Edmonds Entertainment Group (EEG)           1
Shawn Danielle Productions Ltd.             1
Length: 1772, dtype: int64

# 21. Какая студия сняла больше всего фильмов в 2015 году?
Варианты ответа:
1. Universal Pictures
2. Paramount Pictures
3. Columbia Pictures
4. Warner Bros
5. Twentieth Century Fox Film Corporation

In [23]:
answer_ls.append(4)
data_filter=data[data['release_year']==2015]
pd.DataFrame(data_filter.production_companies.str.split('|').tolist()).stack().value_counts()

Warner Bros.                              12
Universal Pictures                        10
Twentieth Century Fox Film Corporation     8
Columbia Pictures                          7
Paramount Pictures                         7
                                          ..
Orange Studios                             1
Ram Bergman Productions                    1
Marc Platt Productions                     1
Prime Focus                                1
Smokehouse Pictures                        1
Length: 246, dtype: int64

# 22. Какая студия заработала больше всего денег в жанре комедий за все время?
Варианты ответа:
1. Warner Bros
2. Universal Pictures (Universal)
3. Columbia Pictures
4. Paramount Pictures
5. Walt Disney

In [28]:
answer_ls.append(3)
data_filter=data[data.genres.str.contains("Comedy", na=False)]
data_filter['profit'] = data['profit'] = data.apply(lambda x: x.revenue - x.budget, axis=1)
data_filter.groupby(['production_companies'])['profit'].sum().sort_values(ascending = False)

C:\Users\asya474\AppData\Roaming\Python\Python37\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until

production_companies
Walt Disney Pictures|Pixar Animation Studios                                                  3396872481
Blue Sky Studios|Twentieth Century Fox Animation                                              2340706751
DreamWorks Animation                                                                          2134172085
Universal Pictures|Illumination Entertainment                                                 1977492847
DreamWorks SKG|Pacific Data Images (PDI)|DreamWorks Animation                                 1486522995
                                                                                                 ...
Conundrum Entertainment|Warner Bros. Animation|Warner Bros.                                    -61403089
Universal Pictures|Original Film|Dark Horse Entertainment                                      -68351500
20th Century Fox|1492 Pictures                                                                 -69590483
Columbia Pictures|Gracie Films|Road Rebel                                                      -71331093
Village Roadshow Pictures|Castle Rock Entertainment|NPV Entertainment|Mel's Cite du Cinema     -92896027
Name: profit, Length: 566, dtype: int64

# 23. Какая студия заработала больше всего денег в 2012 году?
Варианты ответа:
1. Universal Pictures (Universal)
2. Warner Bros
3. Columbia Pictures
4. Paramount Pictures
5. Lucasfilm

In [14]:
answer_ls.append(3)
data['profit'] = data['revenue'] - data['budget']
df_company = pd.DataFrame(data.production_companies.str.split('|').tolist()).stack().reset_index()
df_company.columns = ['row_index','row2','company']
df_company['profit_company'] = df_company.row_index.apply(lambda x : data.iloc[x]['profit'])
df_company['year'] = df_company.row_index.apply(lambda x : data.iloc[x]['release_year'])
df_company.query('year == 2012').groupby('company')['profit_company'].sum().sort_values(ascending = False)

company
Columbia Pictures     2501406608
Universal Pictures    1981011579
Marvel Studios        1299557910
Warner Bros.          1258020056
Relativity Media      1032593938
                         ...
Jouror Productions     -51893525
Onyx Films             -51893525
Transfilm              -51893525
Studio 37              -51893525
France 2 CinÃ©ma       -82545651
Name: profit_company, Length: 236, dtype: int64

# 24. Самый убыточный фильм от Paramount Pictures
Варианты ответа:

1. K-19: The Widowmaker tt0267626
2. Next tt0435705
3. Twisted tt0315297
4. The Love Guru tt0811138
5. The Fighter tt0964517

In [43]:
answer_ls.append(1)
data['profit'] = data['revenue'] - data['budget']
df_company = pd.DataFrame(data.production_companies.str.split('|').tolist()).stack().reset_index()
df_company.columns = ['row_index','row2','company']
df_company['profit_company'] = df_company.row_index.apply(lambda x : data.iloc[x]['profit'])
df_company['title'] = df_company.row_index.apply(lambda x : data.iloc[x]['original_title'])
data_filter=df_company[df_company.company.str.contains("Paramount Pictures", na=False)]
data_filter.groupby('title')['profit_company'].min().sort_values(ascending = False)

title
Transformers: Dark of the Moon                        928746996
Transformers: Revenge of the Fallen                   686297228
Indiana Jones and the Kingdom of the Crystal Skull    601636033
Transformers                                          559709780
Mission: Impossible - Ghost Protocol                  549713380
                                                        ...
Twisted                                               -24805000
Alfie                                                 -46604061
Next                                                  -51788987
Timeline                                              -60519261
K-19: The Widowmaker                                  -64831034
Name: profit_company, Length: 122, dtype: int64

# 25. Какой Самый прибыльный год (заработали больше всего)?
Варианты ответа:
1. 2014
2. 2008
3. 2012
4. 2002
5. 2015

In [49]:
answer_ls.append(5)
data['profit'] = data['revenue'] - data['budget']
data['release_year'].unique()
data.groupby('release_year')['profit'].sum()

release_year
2000     6101399805
2001     7950614865
2002     9002361487
2003     9228823312
2004     9634180720
2005     8981925558
2006     8691077320
2007    11565911801
2008    11663881990
2009    13423744372
2010    13117292530
2011    14730241341
2012    16077001687
2013    15243179791
2014    16397812953
2015    18668572378
Name: profit, dtype: int64

# 26. Какой Самый прибыльный год для студии Warner Bros?
Варианты ответа:
1. 2014
2. 2008
3. 2012
4. 2010
5. 2015

In [51]:
answer_ls.append(1)
data_filter=data[data.production_companies.str.contains("Warner Bros", na=False)]
data_filter['profit'] = data['revenue'] - data['budget']
data_filter.groupby('release_year')['profit'].sum().sort_values(ascending = False)

C:\Users\asya474\AppData\Roaming\Python\Python37\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until

release_year
2014    2295464519
2007    2201675217
2008    2134595031
2010    1974712985
2011    1871393682
2003    1855493377
2009    1822454136
2013    1636453400
2004    1631933725
2005    1551980298
2001    1343545668
2012    1258020056
2002    1022709901
2015     870368348
2006     620170743
2000     452631386
Name: profit, dtype: int64

# 27. В каком месяце за все годы суммарно вышло больше всего фильмов?
Варианты ответа:
1. Январь
2. Июнь
3. Декабрь
4. Сентябрь
5. Май

In [53]:
answer_ls.append(4)
data['release_month'] = pd.to_datetime(data.release_date).apply(lambda x: x.month)
data.groupby('release_month').agg('count').sort_values('imdb_id', ascending = False)

,imdb_id,popularity,budget,revenue,original_title,cast,director,tagline,overview,runtime,genres,production_companies,release_date,vote_count,vote_average,release_year,profit
release_month,,,,,,,,,,,,,,,,,
9,227,227,227,227,227,227,227,227,227,227,227,227,227,227,227,227,227
12,191,191,191,191,191,191,191,191,191,191,191,191,191,191,191,191,191
10,186,186,186,186,186,186,186,186,186,186,186,186,186,186,186,186,186
8,161,161,161,161,161,161,161,161,161,161,161,161,161,161,161,161,161
3,156,156,156,156,156,156,156,156,156,156,156,156,156,156,156,156,156
4,149,149,149,149,149,149,149,149,149,149,149,149,149,149,149,149,149
6,147,147,147,147,147,147,147,147,147,147,147,147,147,147,147,147,147
11,146,146,146,146,146,146,146,146,146,146,146,146,146,146,146,146,146
7,142,142,142,142,142,142,142,142,142,142,142,142,142,142,142,142,142
5,140,140,140,140,140,140,140,140,140,140,140,140,140,140,140,140,140
2,135,135,135,135,135,135,135,135,135,135,135,135,135,135,135,135,135
1,110,110,110,110,110,110,110,110,110,110,110,110,110,110,110,110,110

# 28. Сколько суммарно вышло фильмов летом? (за июнь, июль, август)
Варианты ответа:
1. 345
2. 450
3. 478
4. 523
5. 381

In [56]:
answer_ls.append(2)
data['release_month'] = pd.to_datetime(data.release_date).apply(lambda x: x.month)
data.groupby('release_month').agg('count').sort_values('imdb_id', ascending = False)
len(data[data.release_month.isin([6, 7, 8])])

450

# 29. Какой режисер выпускает (суммарно по годам) больше всего фильмов зимой?
Варианты ответов:
1. Steven Soderbergh
2. Christopher Nolan
3. Clint Eastwood
4. Ridley Scott
5. Peter Jackson

In [58]:
answer_ls.append(5)
data['release_month'] = pd.to_datetime(data.release_date).apply(lambda x: x.month)
data.groupby('release_month').agg('count').sort_values('imdb_id', ascending = False)           
data[data.release_month.isin([1, 2, 12])].groupby('director').agg('count').sort_values('imdb_id', ascending=False)

,imdb_id,popularity,budget,revenue,original_title,cast,tagline,overview,runtime,genres,production_companies,release_date,vote_count,vote_average,release_year,profit,release_month
director,,,,,,,,,,,,,,,,,
Peter Jackson,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7
Steven Soderbergh,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6
Clint Eastwood,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6
Adam Shankman,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4
Nancy Meyers,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
GÃ¡bor CsupÃ³,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
Guy Ritchie,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
Guy Ferland,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
Gus Van Sant,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
Will Gluck,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1

# 30. Какой месяц чаще всего по годам самый прибыльный?
Варианты ответа:
1. Январь
2. Июнь
3. Декабрь
4. Сентябрь
5. Май

In [62]:
answer_ls.append(2)
data['release_month']=pd.to_datetime(data.release_date).apply(lambda x:x.month)
time_data=data.groupby(['release_year', 'release_month']).agg('sum')
time_maxes=time_data.groupby('release_year').agg('max')[['profit']].rename(columns={"profit":"max_profit"})
time_data.reset_index(inplace=True)
time_data=time_data.merge(time_maxes, on='release_year')
time_data[time_data.profit==time_data.max_profit].release_month.value_counts().sort_values(ascending=False)

6     7
5     4
12    4
7     1
Name: release_month, dtype: int64

# 31. Названия фильмов какой студии в среднем самые длинные по количеству символов?
Варианты ответа:
1. Universal Pictures (Universal)
2. Warner Bros
3. Jim Henson Company, The
4. Paramount Pictures
5. Four By Two Productions

In [66]:
answer_ls.append(1)
data['nlen'] = data.original_title.apply(len)
df_company = pd.DataFrame(data.production_companies.str.split('|').tolist()).stack().reset_index()
df_company.columns = ['row_index','row2','company']
df_company['nlen'] = df_company.row_index.apply(lambda x : data.iloc[x]['nlen'])
df_company['title'] = df_company.row_index.apply(lambda x : data.iloc[x]['original_title'])
df_company.groupby('company').agg('mean').sort_values('nlen', ascending=False)

                            row_index  row2  nlen
company
Four By Two Productions        1449.0   1.0  83.0
Jim Henson Company, The         219.0   2.0  59.0
Dos Corazones                  1067.0   0.0  47.0
Polsky Films                    330.0   4.0  46.0
Museum Canada Productions       265.0   4.0  46.0
...                               ...   ...   ...
Everest Entertainment          1277.0   1.0   3.0
Berlanti Productions             64.0   2.0   3.0
Global Entertainment Group      715.0   2.0   2.0
XM2 Productions                1173.0   4.0   2.0
Ixtlan Productions              715.0   0.0   2.0

[1772 rows x 3 columns]

# 32. Названия фильмов какой студии в среднем самые длинные по количеству слов?
Варианты ответа:
1. Universal Pictures (Universal)
2. Warner Bros
3. Jim Henson Company, The
4. Paramount Pictures
5. Four By Two Productions

In [87]:
answer_ls.append(5)

data['word_len'] = data.original_title.apply(lambda x: len(x.split()))
df_company = pd.DataFrame(data.production_companies.str.split('|').tolist()).stack().reset_index()
df_company.columns = ['row_index','row2','company']
df_company['word_len'] = df_company.row_index.apply(lambda x : data.iloc[x]['wlen'])
df_company['title'] = df_company.row_index.apply(lambda x : data.iloc[x]['original_title'])
df_company.groupby('company').agg('mean').sort_values('word_len', ascending=False).head(20)

                                   row_index  row2  word_len
company
Four By Two Productions               1449.0   1.0      12.0
Jim Henson Company, The                219.0   2.0      10.0
Dos Corazones                         1067.0   0.0       9.0
Polsky Films                           330.0   4.0       9.0
The Saul Zaentz Company                680.5   2.0       9.0
TSBD Canada Productions                752.0   3.0       8.0
Zohar International                    752.0   4.0       8.0
Cool Music                            1671.0   0.0       8.0
3Foot7                                 123.0   2.0       8.0
Harry Potter Publishing Rights        1671.0   3.0       8.0
Lucasfilm                              699.0   0.0       8.0
Museum Canada Productions              265.0   4.0       8.0
Total Entertainment                    752.0   2.0       8.0
Samuel Goldwyn Films                  1155.5   2.5       7.5
Iron Film                             1501.0   2.0       7.0
P of A Productions Limited            1561.0   3.0       7.0
MIRACLE Productions GmbH & Co. KG      865.0   3.0       7.0
Crying Box Productions                 681.0   3.0       7.0
Lipsync Productions                    719.0   4.0       7.0
Chris Brinker Productions              329.0   0.0       7.0

# 33. Сколько разных слов используется в названиях фильмов?(без учета регистра)
Варианты ответа:
1. 6540
2. 1002
3. 2461
4. 28304
5. 3432

In [68]:
answer_ls.append(3)
lower_words = pd.DataFrame(data.original_title.str.lower())
lower_words = pd.DataFrame(lower_words.original_title.str.split(' ').tolist()).stack().reset_index()
lower_words.columns = ['row1', 'row2', 'words']
lower_words['words'].nunique()

2462

# 34. Какие фильмы входят в 1 процент лучших по рейтингу?
Варианты ответа:
1. Inside Out, Gone Girl, 12 Years a Slave
2. BloodRayne, The Adventures of Rocky & Bullwinkle
3. The Lord of the Rings: The Return of the King
4. 300, Lucky Number Slevin

In [88]:
answer_ls.append(1)
data.sort_values(by='vote_average', ascending=False).head(int(len(data)*0.01)+1)['original_title']

600                                       The Dark Knight
125                                    The Imitation Game
9                                              Inside Out
118                                          Interstellar
34                                                   Room
1082        The Lord of the Rings: The Return of the King
873                                           The Pianist
1801                                              Memento
1192                                     12 Years a Slave
128                                             Gone Girl
138                              The Grand Budapest Hotel
119                               Guardians of the Galaxy
1184                              The Wolf of Wall Street
370                                             Inception
316                                              3 Idiots
1564                Eternal Sunshine of the Spotless Mind
497     The Lord of the Rings: The Fellowship of the Ring
28                                              Spotlight
1214                                   Dallas Buyers Club
Name: original_title, dtype: object

# 35. Какие актеры чаще всего снимаются в одном фильме вместе
Варианты ответа:
1. Johnny Depp & Helena Bonham Carter
2. Hugh Jackman & Ian McKellen
3. Vin Diesel & Paul Walker
4. Adam Sandler & Kevin James
5. Daniel Radcliffe & Rupert Grint

In [24]:
answer_ls.append(1)
_actors=collections.Counter()
for i, d in data.iterrows():
    _a = d.cast.split('|')
    _actors.update([ x for x in itertools.combinations(_a, 2)])
_actors.most_common(5)

[(('Daniel Radcliffe', 'Rupert Grint'), 8),
 (('Daniel Radcliffe', 'Emma Watson'), 8),
 (('Rupert Grint', 'Emma Watson'), 7),
 (('Ben Stiller', 'Owen Wilson'), 6),
 (('Johnny Depp', 'Helena Bonham Carter'), 6)]

# 36. У какого из режиссеров выше вероятность выпустить фильм в прибыли? (5 баллов)101
Варианты ответа:
1. Quentin Tarantino
2. Steven Soderbergh
3. Robert Rodriguez
4. Christopher Nolan
5. Clint Eastwood

In [28]:
answer_ls.append(4)
data['profit'] = data.apply(lambda x: x.revenue - x.budget, axis=1)
maker_films = []
for index,f in data.iterrows():
    for d in f.director.split('|'):
        maker_films += [(f.imdb_id, d)]
directors_df = pd.DataFrame(maker_films, columns=['imdb_id', 'single_director'])
directors_df.describe()
count_y = lambda x: len([ i for i in x if i  > 0])
count_n = lambda x: len([ i for i in x if i <= 0])
data['profit_y'] = data['profit']
data['profit_n'] = data['profit']
filter=['Quentin Tarantino', 'Steven Soderbergh', 'Robert Rodriguez', 'Christopher Nolan', 'Clint Eastwood']
res=directors_df.merge(data, on='imdb_id').groupby('single_director').aggregate({"imdb_id": len, "profit_y": count_y, "profit_n": count_n})
res['p'] = res.profit_y / res.imdb_id
res.sort_values(by='p', ascending=False)
res.reset_index(inplace=True)
res[res.single_director.isin(filter)].sort_values(by='p', ascending=False)

       single_director  imdb_id  profit_y  profit_n         p
151  Christopher Nolan        8         8         0  1.000000
748  Quentin Tarantino        7         6         1  0.857143
157     Clint Eastwood       12        10         2  0.833333
902  Steven Soderbergh       13        10         3  0.769231
791   Robert Rodriguez       11         8         3  0.727273

# Submission

In [54]:
len(answer_ls)

41

In [55]:
pd.DataFrame({'Id':range(1,len(answer_ls)+1), 'Answer':answer_ls}, columns=['Id', 'Answer'])

    Id  Answer
0    1       1
1    2       1
2    3       1
3    4       1
4    5       1
5    6       1
6    7       1
7    8       1
8    9       1
9   10       1
10  11       1
11  12       1
12  13       1
13  14       1
14  15       1
15  16       1
16  17       1
17  18       1
18  19       1
19  20       4
20  21       4
21  22       2
22  23       3
23  24       2
24  25       1
25  26       5
26  27       2
27  28       1
28  29       4
29  30       5
30  31       3
31  32       1
32  33       3
33  34       4
34  35       3
35  36       3
36  37       2
37  38       4
38  39       5
39  40       1
40  41       3